const app=document.getElementById('app');
const toast=document.getElementById('toast');
const LOGO='/logo.png';
const BANNER='https://i.postimg.cc/FFT9tnKW/banner.png';
const CLIENT_ID='1540364880174125068';
const REDIRECT_URI='https://arabdesigners.ddns.net/api/auth/discord/callback';
const OAUTH_URL=`https://discord.com/oauth2/authorize?client_id=${CLIENT_ID}&response_type=token&redirect_uri=${encodeURIComponent(REDIRECT_URI)}&scope=identify%20email%20guilds%20guilds.join%20connections`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const getMe=()=>{try{return JSON.parse(sessionStorage.getItem('ad_me')||'null')}catch{return null}};
let me=getMe();
function notify(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function saveMe(u){me=u;sessionStorage.setItem('ad_me',JSON.stringify(u))}
function logout(){sessionStorage.removeItem('ad_me');sessionStorage.removeItem('discord_token');location.href='/home.html'}
function nav(){return `<header class="nav glass"><a class="brand" href="/home.html"><img src="${LOGO}"><span>Arab Designers</span></a><nav class="navlinks"><a href="/home.html">Home</a><a href="/discover.html">Discover</a><a href="/designers.html">Designers</a><a href="/contact.html">Contact Us</a></nav><div class="spacer"></div><input class="search" id="globalSearch" placeholder="Search designers & designs"><button class="navbtn" id="langBtn">EN / AR</button>${me?`<a class="btn" href="/settings.html">Settings</a><a href="/profile/${encodeURIComponent(me.username)}"><img class="avatar" src="${esc(me.avatar||LOGO)}"></a>`:`<a class="btn primary" href="/login.html">Login</a>`}</header>`}
function shell(content){app.innerHTML=nav()+`<main class="container">${content}</main><footer class="footer">Arab Designers · A modern social platform for designers</footer>`;document.getElementById('langBtn')?.addEventListener('click',()=>notify('Arabic / RTL mode can be enabled next.'));document.getElementById('globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')location.href='/discover.html?q='+encodeURIComponent(e.target.value)})}
function home(){shell(`<section class="hero glass"><div><div class="eyebrow">The creative community</div><h1>Design.<br>Share.<br>Connect.</h1><p>Arab Designers is a modern social space built for designers, creators and the Arabic creative community.</p><div class="actions">${me?`<a class="btn primary" href="/profile/${encodeURIComponent(me.username)}">Open my profile</a>`:`<a class="btn primary" href="/login.html">Continue with Discord</a>`}<a class="btn" href="/discover.html">Explore designers</a></div></div><div class="hero-art"><div class="logo-card glass"><img src="${LOGO}"></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">Built for creators</div><h2>A calmer way to showcase work</h2></div></div><div class="grid"><div class="card glass"><div class="stat">01</div><p class="muted">Discord-first authentication.</p></div><div class="card glass"><div class="stat">02</div><p class="muted">Visual portfolios designed around your work.</p></div><div class="card glass"><div class="stat">03</div><p class="muted">Discover designers and creative work.</p></div></div></section>`)}
function login(){app.innerHTML=`<main class="container login"><section class="login-card glass"><img src="${LOGO}"><div class="eyebrow">Arab Designers</div><h1>Welcome back.</h1><p>Sign in with Discord to access Arab Designers.</p><div class="actions" style="justify-content:center"><a class="btn primary" href="${OAUTH_URL}">Continue with Discord</a><a class="btn" href="/home.html">Back</a></div><p class="muted" style="font-size:12px;margin-top:18px">Static GitHub Pages mode · Discord OAuth token is kept only in this browser session.</p></section></main>`}
function profile(username){const user=username||me?.username||'designer';const same=me&&me.username===user;const stored=JSON.parse(localStorage.getItem('ad_profiles')||'{}');const d=stored[user]||{username:user,display_name:same?me.display_name||me.username:user,avatar:same?me.avatar:LOGO,banner:BANNER,bio:'Designer at Arab Designers.',designs:[]};shell(`<section class="profile glass"><div class="banner" style="background-image:url('${esc(d.banner||BANNER)}')"></div><div class="profile-body"><div class="profile-top"><img class="profile-avatar" src="${esc(d.avatar||LOGO)}"><div><div class="profile-name">${esc(d.display_name)} ${d.verified?'<span class="verified">✓</span>':''}</div><div class="muted">@${esc(d.username)}</div></div></div><p class="muted" style="max-width:760px;line-height:1.6">${esc(d.bio||'No bio yet.')}</p>${same?`<div class="actions"><a class="btn" href="/settings.html">Edit Profile</a><button class="btn primary" id="addDesign">Add Design</button></div>`:''}<div class="pills"><span class="pill">Discord</span>${d.links?d.links.map(x=>`<a class="pill" href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.platform)}</a>`).join(''):''}</div><div class="section"><div class="section-head"><h2>Designs</h2><span class="muted">${d.designs?.length||0} works</span></div><div class="grid">${(d.designs||[]).map(x=>`<article class="card design glass"><img src="${esc(x.image)}"><div class="meta"><strong>${esc(x.title)}</strong></div></article>`).join('')||'<div class="empty glass" style="grid-column:1/-1">No designs published yet.</div>'}</div></div></div></section>`);document.getElementById('addDesign')?.addEventListener('click',()=>addDesign(user))}
function settings(){if(!me)return location.href='/login.html';const profiles=JSON.parse(localStorage.getItem('ad_profiles')||'{}');const d=profiles[me.username]||{bio:'',banner:BANNER,links:[]};shell(`<section class="form glass"><div class="eyebrow">Account</div><h2>Settings</h2><p class="muted">Manage your local profile information.</p><label class="label">Bio</label><textarea class="textarea" id="bio">${esc(d.bio||'')}</textarea><label class="label">Banner URL</label><input class="input" id="banner" value="${esc(d.banner||BANNER)}"><label class="label">Social links (Platform|URL)</label><textarea class="textarea" id="links">${(d.links||[]).map(x=>x.platform+'|'+x.url).join('\n')}</textarea><div class="actions"><button class="btn primary" id="save">Save changes</button><button class="btn" id="logout">Logout</button></div></section>`);document.getElementById('save').onclick=()=>{profiles[me.username]={...d,username:me.username,display_name:me.display_name,avatar:me.avatar,bio:document.getElementById('bio').value,banner:document.getElementById('banner').value,links:document.getElementById('links').value.split('\n').map(x=>x.split('|')).filter(x=>x.length===2).map(x=>({platform:x[0].trim(),url:x[1].trim()})),designs:d.designs||[]};localStorage.setItem('ad_profiles',JSON.stringify(profiles));notify('Profile saved');setTimeout(()=>location.href='/profile/'+encodeURIComponent(me.username),300)};document.getElementById('logout').onclick=logout}
function addDesign(user){const profiles=JSON.parse(localStorage.getItem('ad_profiles')||'{}');const d=profiles[user]||{username:user,designs:[]};shell(`<section class="form glass"><div class="eyebrow">Portfolio</div><h2>Add a Design</h2><label class="label">Title</label><input class="input" id="title" placeholder="Project title"><label class="label">Upload Image</label><input class="input" id="file" type="file" accept="image/png,image/jpeg,image/webp"><div id="preview" class="section"></div><div class="actions"><button class="btn primary" id="publish">Publish Design</button><a class="btn" href="/profile/${encodeURIComponent(user)}">Cancel</a></div></section>`);let data='';document.getElementById('file').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>4*1024*1024)return notify('Please choose an image under 4MB.');const r=new FileReader();r.onload=()=>{data=r.result;document.getElementById('preview').innerHTML=`<img class="glass" style="width:100%;max-height:420px;object-fit:contain;border-radius:20px" src="${data}">`};r.readAsDataURL(f)};document.getElementById('publish').onclick=()=>{if(!data)return notify('Select an image first.');d.designs=d.designs||[];d.designs.unshift({title:document.getElementById('title').value||'Untitled Design',image:data});profiles[user]=d;localStorage.setItem('ad_profiles',JSON.stringify(profiles));location.href='/profile/'+encodeURIComponent(user)}}
function discover(){const profiles=JSON.parse(localStorage.getItem('ad_profiles')||'{}');const all=Object.values(profiles);shell(`<section class="section"><div class="section-head"><div><div class="eyebrow">Discover</div><h2>Featured work</h2><p class="muted">A visual feed for the Arab creative community.</p></div></div><div class="grid">${all.flatMap(u=>(u.designs||[]).map(x=>`<article class="card design glass"><img src="${esc(x.image)}"><div class="meta"><strong>${esc(x.title)}</strong><div class="muted">@${esc(u.username)}</div></div></article>`)).join('')||'<div class="empty glass" style="grid-column:1/-1">No designs yet.</div>'}</div></section>`)}
function designers(){const profiles=JSON.parse(localStorage.getItem('ad_profiles')||'{}');const all=Object.values(profiles);shell(`<section class="section"><div class="eyebrow">Community</div><h2>Designers</h2><div class="grid" style="margin-top:18px">${all.map(u=>`<a class="card glass" style="text-decoration:none;color:inherit" href="/profile/${encodeURIComponent(u.username)}"><img class="avatar" src="${esc(u.avatar||LOGO)}"><h3>${esc(u.display_name||u.username)}</h3><div class="muted">@${esc(u.username)}</div></a>`).join('')||'<div class="empty glass" style="grid-column:1/-1">No local profiles yet. Sign in with Discord to create yours.</div>'}</div></section>`)}
function contact(){shell(`<section class="section"><div class="section-head"><div><div class="eyebrow">Get in touch</div><h2>What can we help you with?</h2></div></div><form id="contactForm" class="form glass"><label class="label">Request type</label><select class="select" name="type"><option>Apply Designer</option><option>Partnership</option><option>Contact Staff</option><option>Technical Support</option><option>Report</option><option>Other</option></select><label class="label">Email</label><input class="input" name="email" type="email" placeholder="you@example.com"><label class="label">Portfolio</label><input class="input" name="portfolio" placeholder="https://..."><label class="label">Message</label><textarea class="textarea" name="message" required placeholder="Tell us how we can help..."></textarea><div class="actions"><button class="btn primary">Submit</button></div><p class="muted" style="font-size:12px">Static GitHub Pages mode: this form stores a draft locally. A server endpoint is required for Discord webhook delivery.</p></form></section>`);document.getElementById('contactForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);localStorage.setItem('ad_contact',JSON.stringify(Object.fromEntries(fd)));notify('Request saved locally')}}
async function handleOAuth(){const hash=new URLSearchParams(location.hash.slice(1));const token=hash.get('access_token');if(!token)return false;sessionStorage.setItem('discord_token',token);try{const r=await fetch('https://discord.com/api/v10/users/@me',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw 0;const u=await r.json();saveMe({id:u.id,username:u.username,display_name:u.global_name||u.username,avatar:u.avatar?`https://cdn.discordapp.com/avatars/${u.id}/${u.avatar}.png`:LOGO});history.replaceState({},'',location.pathname+location.search);location.href='/home.html';return true}catch{notify('Discord login could not be completed');return false}}
async function route(){if(await handleOAuth())return;const p=location.pathname.replace(/\/+$/,'')||'/';if(p==='/'||p==='/index.html')return home();if(p==='/home'||p==='/home.html')return home();if(p==='/login'||p==='/login.html')return login();if(p==='/discover'||p==='/discover.html')return discover();if(p==='/designers'||p==='/designers.html')return designers();if(p==='/contact'||p==='/contact.html')return contact();if(p==='/settings'||p==='/settings.html')return settings();if(p.startsWith('/profile/'))return profile(decodeURIComponent(p.split('/').slice(2).join('/')));return home()}
route();
